version: 0.2

phases:
  pre_build:
    commands:
      - echo Building the Docker image...           
      - docker build -t helloworld .
  build:
    commands:
      - echo Build started on `date`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker tag helloworld:latest 031342435657.dkr.ecr.ap-south-1.amazonaws.com/cicdtest:gwell   
      - docker images  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 031342435657.dkr.ecr.ap-south-1.amazonaws.com/cicdtest:gwell
